{% set name = "xpa" %}
{% set version = "2.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ericmandel/xpa/archive/{{ version }}.tar.gz
  sha256: 854af367c0f4ffe7a65cb4da854a624e20af3c529f88187b50b22b68f024786a
  patches:
    - add-ldflags-shlib.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libxpa.a
    - test -f ${PREFIX}/lib/libxpa${SHLIB_EXT}

about:
  home: https://github.com/ericmandel/xpa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: seamless communication between many kinds of Unix programs, including X programs and Tcl/Tk programs.

extra:
  recipe-maintainers:
    - beckermr
